# July 2025/rajeshvs
name: ai-llm-on-ucs-webui
services: 
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
        - WEBUI_AUTH=false
        - WEBUI_NAME=Cisco dCloud
        - OPENAI_API_KEY=dummy
        - OPENAI_API_BASE_URL=http://${API_IP}:5000/v1
        - DEFAULT_MODELS=gpt-3.5-turbo
        - RAG_EMBEDDING_MODEL=sentence-transformers/paraphrase-MiniLM-L6-v2
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: all
                      capabilities:
                          - gpu
volumes:
  open-webui: 